<?php

require_once 'square.php';

/**
 * Contains the classes Move and MoveException
 */

/**
 * A class respresenting a exception thrown by Move
 *
 * List of Exception Codes:
 *  1: Unknown internal error
 *  2: Empty/Null argument
 *  3: Wrong argument count
 *  4: Wrong argument type
 *  5: Invalid argument value (general)
 *  6: Invalid argument syntax (strings)
 *  7: Numerical argument outside of allowed range
 */

class MoveException extends Exception {}

/**
 * A class respresenting a chess move.
 */

class Move
{

	/**
	 * The departure square.
	 *
	 * This is an integer generated by string2square()
	 */

	private $departure;

	/**
	 * The destination square.
	 *
	 * This is an integer generated by string2square()
	 */

	private $destination;

	/**
	 * Constructor of Move.
	 *
	 * Sets up all private variables.
	 *
	 * @param mixed $departure square of departure; can be: string ('a1'), integer generated by string2square (0) or array ([$file, $rank) with file and rank count starting at zero
	 * @param mixed $destination destination square; can be: string ('a1'), integer generated by string2square (0) or array ([$file, $rank) with file and rank count starting at zero
	 */

	function __construct($departure, $destination)
	{

	}

	/**
	 * Returns the departure square.
	 *
	 * You can specify the format you want the square to be returned in.
	 *
	 * @param int $format the format for the square; can be SQUARE_FORMAT_INT, SQUARE_FORMAT_STRING or SQUARE_FORMAT_ARRAY
	 */

	function getDeparture($format = SQUARE_FORMAT_INT)
	{

	}

	/**
	* Returns the destination square.
	*
	* You can specify the format you want the square to be returned in.
	*
	* @param int $format the format for the square; can be SQUARE_FORMAT_INT, SQUARE_FORMAT_STRING or SQUARE_FORMAT_ARRAY
	*/

	function getDestination($format = SQUARE_FORMAT_INT)
	{

	}
}

?>
